placeholder:
  - template_project_python
  - template-project-python

update_files:
  - docs/src/index.rst
  - docs/src/conf.py
  - .gitattributes
  - README.md
  - MANIFEST.in
  - setup.cfg
  - setup.py
  - tox.ini
  - pyinstaller.spec
  - template_project_python/__main__.py
  - template_project_python/main.py
  - scripts/pyinstaller_entry_point.py

rename_files:
  - template_project_python_config.json

rename_dirs:
  - template_project_python/

remove_files:
  - template_config.yaml
  - .github/workflows/test_template_initializer.yaml

remove_dirs:
